import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Locale } from "../../../i18n.config";
import { getDictionary } from "../../../lib/dictionary";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "World Pool Championship",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: { lang: Locale };
  children: React.ReactNode;
}>) {
  const { page } = await getDictionary(params.lang);

  return (
    <html lang={params.lang} dir={params.lang === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${params.lang === 'ar' ? 'font-arabic' : ''}`}
      >
      <Navbar lang={params.lang} table={page}/>
        {children}
      </body>
    </html>
  );
}